# roles/mariadb/tasks/users.yml
---
# It does not appear that there are any anonymous users in the RHEL mariadb packages.
#- name: Remove anonymous users
#  community.mysql.mysql_user:
#    name: ""
#    host_all: true
#    login_user: root
#    login_password: "{{ mariadb_vault_root_pw }}"
#    login_unix_socket: "{{ mariadb_srv_socket }}"
#    state: absent
#  tags: mariadb
#  no_log: true

- name: Create the users
  loop: "{{ mariadb_users }}"
  tags: mariadb
  no_log: true
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host|default('localhost') }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs|default('no') }}"
    login_user: root
    login_password: "{{ mariadb_vault_root_pw }}"
    login_unix_socket: "{{ mariadb_srv_socket }}"
    state: present

