---

- name: Create configdump base directory
  ansible.builtin.file:
    path: "{{ configdump_dict.base }}"
    state: directory
    owner: "{{ kf_ejbca_user }}"
    group: "{{ kf_ejbca_group }}"
    mode: '0750'

- name: Create sub directories
  loop: "{{ configdump_dict.dirs.keys() }}"
  ansible.builtin.file:
    path: "{{ configdump_dict.base }}/{{ item }}"
    state: directory
    owner: "{{ kf_ejbca_user }}"
    group: "{{ kf_ejbca_group }}"
    mode: '0750'

- name: Template config files
  loop: "{{ configdump_dict.dirs|dict2items|subelements('value') }}"
  loop_control:
    label: "{{ item[1] }}"
  ansible.builtin.template:
    src: "{{ item[1] }}"
    dest: "{{ configdump_dict.base }}/{{ item[0].key }}/{{ item[1] }}"
    owner: "{{ kf_ejbca_user }}"
    group: "{{ kf_ejbca_group }}"
    mode: '0640'

- name: Import staged configuration
  register: config_import
  become_user: "{{ kf_ejbca_user }}"
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/dist/configdump/configdump.sh import 
    --ignore-errors 
    --overwrite update 
    --non-interactive continue 
    {% if initialize|default(true) %}
    --initialize
    {% endif %}
    -l "{{ configdump_dict.base }}"

- name: Clean up configuration folder
  ansible.builtin.file:
    path: "{{ configdump_dict.base }}"
    state: absent

