---

# ansible-playbook -i inventory -l eeCaServers,ca01 deployExtRootCaForSubPart3.yml

- hosts: pkiServers
  become: yes
  become_method: sudo
  vars:
    deploy_with_configdump: false
    add_certification_authorities: "{{ sub_add_certification_authorities }}"
  roles:
    - ansible-ejbca-deploy-pki-ext-signed-sub-1