---

# ansible-playbook -i inventory -l eeCaServers,ca01 deployExtRootCaForSubPart1.yml

- hosts: pkiServers
  become: yes
  become_method: sudo
  vars:
    deploy_with_configdump: true
    configdump_directory_structure: "{{ configdump_dir_structure }}"
    configdump_import_files: "{{ configdump_files }}"
  roles:
    - ansible-hostname
    - ansible-role-mariadb
    - ansible-ejbca-wildfly
    - ansible-ejbca-pkc11-client
    - ansible-ejbca-prep
    - ansible-ejbca-deploy-pki-ca-node-mgmt-ca
    - ansible-pki-httpd
