---

- name: Configure TLS, Peering, and OCSP
  become: true
  hosts: ejbca_servers
  pre_tasks: 

    - name: Include variables role
      ansible.builtin.import_role:
        name: fpki_roles_kfvariables
        
  tasks:

    - name: Update OCSP Presigner after {{ kf_cas_sub.name }} is ACTIVE
      when: inventory_hostname in groups['certificate_authorities'][0]
      ansible.builtin.include_role:
        name: fpki_roles_kfca
        tasks_from: update_presigner.yml

    - name: Create Remote Authentication key binding
      when: inventory_hostname in groups['certificate_authorities'][0]
      run_once: true
      loop: ["{{ kf_keybind.peering }}"]
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.include_role:
        name: fpki_roles_kfoperations
        tasks_from: create_key_binding.yml
        apply:
          become_user: "{{ kf_ejbca.user.name }}"

    - name: Import ocsp configuration on VA Servers
      when: inventory_hostname in groups['validation_authorities']
      vars:
        configdump_dict: "{{ kf_configdump.ocsp_config_va }}"
      ansible.builtin.include_role:
        name: fpki_roles_kfconfigdump

    - name: Configure Peering
      ansible.builtin.include_role:
        name: fpki_roles_kfpeering
