# roles/mariadb/tasks/config.yml
---

- name: Configure swappiness
  when: mariadb_configure_swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present

- name: Ensure service is started and enabled
  ansible.builtin.systemd:
    name: mariadb.service
    state: started
    enabled: true