---

- name: Upload CA certificate from Ansible Controller
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/ejbcaCerts/{{ item.name }}.pem"
    dest: "{{ kf_ejbca_home }}/certificates/{{ item.name }}.pem"
    owner: "{{ kf_ejbca_user.name }}"
    group: "{{ kf_ejbca_user.group }}"

- name: Import External CA - {{ item.name }}
  register: import_external_ca
  failed_when: 
    - import_external_ca.rc >= 1
    - not import_external_ca is search('already exists and is not waiting for certificate response')
    - not import_external_ca is search('The CA certificate chain is already imported')
  become_user: "{{ kf_ejbca_user.name }}"
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh ca importcacert
    --caname {{ item.name }}
    -f "{{ kf_ejbca_home }}/certificates/{{ item.name }}.pem"

  # TODO Look into if the rc should be 1 instead of 2.
  