---

- name: Get current CAs on {{ inventory_hostname }}
  register: current_cas
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh ca listcas

- name: Import External CA certificates
  when: not current_cas.stdout is search(item)
  loop: "{{ cas_to_import }}"
  register: import_external_ca
  failed_when: 
    - import_external_ca.rc >= 1
    - not import_external_ca is search('already exists and is not waiting for certificate response')
    - not import_external_ca is search('The CA certificate chain is already imported')
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh ca importcacert
    --caname {{ item }}
    -f "{{ kf_ejbca_home }}/certificates/{{ item }}.pem"

  # TODO Look into if the rc should be 1 instead of 2.
  