---

- name: Create peer systems for Peer servers
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh peer create
    --name "{{ item }}"
    --state enabled
    --url '"https://{{ item }}/ejbca/peer/v1"'
    --akb "{{ kf_keybind.peering.name }}"

- name: Configure Incoming requests if peer is an RA
  when: item in groups['registration_authorities']
  block:

  - name: List peer systems to get Peer ID
    register: listpeers
    ansible.builtin.command: >
      {{ kf_ejbca_home }}/bin/ejbca.sh peer list

  - name: Get ID from peer output
    register: peer_id
    when: line is search('l-tlsocsp4')
    loop: "{{ listpeers.stdout_lines }}"
    loop_control:
      loop_var: line
    ansible.builtin.set_fact:
      peer_id: "{{ line.split()[1] }}"

  - name: Configure Incoming request on {{ peer_id }} # fails if peer name includes whitespace
    ansible.builtin.command: >
      {{ kf_ejbca_home }}/bin/ejbca.sh peer edit 
      --id {{ peer_id }}
      --process-incoming-requests true 
      --max-parallel-requests '50' 
      --min-parallel-requests '2'
