---

- name: Configure Remote Peer Systems
  when: inventory_hostname in groups['peer_servers']
  block:

    - name: Import configdump configuration on Peer Servers using configdump structure defined in inventory
      vars:
        import_path: "{{ kf_ejbca_home }}/peer-server-dump"
      ansible.builtin.include_tasks:
        file: import_config_dump.yml
        
    - name: Configure Peer system global settings
      register: global_peer_config_vas
      failed_when:
        - not global_peer_config_vas.stdout is search('Disabled outgoing peer connections')
        - not global_peer_config_vas.stdout is search('Enabled incoming peer connections')
      ansible.builtin.command: >
        {{ kf_ejbca_home }}/bin/ejbca.sh peer config
        --enable-in 'true'
        --enable-out 'false'

- name: Configure Peering on CA
  when: inventory_hostname in groups['certificate_authorities'][0] 
  run_once: true
  block:

    - name: Configure CA global peer settings
      register: global_peer_config_cas
      failed_when:
        - not global_peer_config_cas.stdout is search('Disabled incoming peer connections')
        - not global_peer_config_cas.stdout is search('Enabled outgoing peer connections')
      ansible.builtin.command: >
        {{ kf_ejbca_home }}/bin/ejbca.sh peer config
        --enable-in 'false'
        --enable-out 'true'

    - name: Create peer connections and publishers on CA host
      vars:
        import_path: "{{ kf_ejbca_home }}/config-peers"
      include_tasks: create_peers_pubs.yml
