---

- name: Configure Registration Authority Peer Role member on CA
  block:

    - name: Get Apache TLS serial number from Apache public certificate file path on Peer host
      register: cert_serial_number
      ansible.builtin.command: >
        openssl x509 -noout -serial -in {{ kf_httpd_config.tls.public.path }}

    - name: Store serial number from {{ item }} in fact to use on CA host
      when: inventory_hostname in groups['registration_authorities']
      ansible.builtin.set_fact: 
        cert_serial_number: "{{ cert_serial_number.stdout.split('=')[1] }}"

    - name: Add RA peer TLS certificate to RA peering role on CA host using loop item hostvars 'cert_serial_number'
      when: inventory_hostname in groups['certificate_authorities'][0]
      register: add_peer_member
      run_once: true
      failed_when:
        - add_peer_member.rc >= 1
        - not add_peer_member is search('was not added because it already exists')
      loop: "{{ groups['registration_authorities'] }}"
      ansible.builtin.command: >
        {{ kf_ejbca_home }}/bin/ejbca.sh roles addrolemember
        --role "{{ kf_peering_ra_role }}"
        --caname "{{ kf_cas_mgmt.name }}"
        --with WITH_SERIALNUMBER
        --value "{{ hostvars[item]['cert_serial_number'] }}"
        --description {{ item }}

- name: Add CA Peer to RA/VA Nodes
  block:

    - name: Get Peering Key Binding serial number
      when: inventory_hostname in groups['certificate_authorities'][0] 
      block:

        - name: Export Peering keybinding certificate to local directory for dumping with Openssl
          register: listkeybindings
          ansible.builtin.command: >
            {{ kf_ejbca_home }}/bin/ejbca.sh keybind exportcert
            --name "{{ kf_peering_remote_auth.name }}"
            -f "{{ kf_ejbca_home }}/certificates/{{ kf_peering_remote_auth.name }}"

        - name: Get serial number from exported certificate
          register: cert_serial_number
          ansible.builtin.command: >
            openssl x509 -noout -serial -in "{{ kf_ejbca_home }}/certificates/{{ kf_peering_remote_auth.name }}"

        - name: Store serial number and inventory_hostname for CA host fact to use on Peering hosts
          ansible.builtin.set_fact: 
            cert_serial_number: "{{ cert_serial_number.stdout.split('=')[1] }}"

    - name: Add CA peer TLS certificate using first CA host in 'certificate_authorities' to CA peering role on RA and VA host
      when: inventory_hostname in groups['peer_servers']
      register: add_peer_member
      failed_when:
        - add_peer_member.rc >= 1
        - not add_peer_member is search('was not added because it already exists')
      ansible.builtin.command: >
        {{ kf_ejbca_home }}/bin/ejbca.sh roles addrolemember
        --role "{{ kf_peering_ca_role }}"
        --caname "{{ kf_cas_mgmt.name }}"
        --with WITH_SERIALNUMBER
        --value "{{ hostvars[groups['certificate_authorities'][0]]['cert_serial_number'] }}"
        --description ca-peer




