---

- name: Create certificate and csr folders if they dont already exist
  loop:
    - "{{ kf_ejbca_home }}/certificates"
    - "{{ kf_ejbca_home }}/csr"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ kf_ejbca_user }}"
    group: "{{ kf_ejbca_group }}"
    state: directory
    mode: '0770'

- name: Extract list of inventory hostname from each host so the are available on {{ groups['certificate_authorities'][0] }}
  run_once: true
  ansible.builtin.set_fact:
    ansible_host_fqdns: "{{ ansible_play_hosts|map('extract',hostvars,'ansible_fqdn') }}"

- name: Create, or reissue ACTIVE, TLS certificates for each host in 'ansible_host_fqdns' on {{ groups['certificate_authorities'][0] }}
  when: inventory_hostname in groups['certificate_authorities'][0]
  loop: "{{ ansible_host_fqdns }}"
  run_once: true
  vars:
    end_entity_reset: true
  ansible.builtin.include_tasks: 
    file: create_tls_certs.yml
  
- name: Configure HTTPD on all EJBCA servers
  nsible.builtin.include_tasks: 
    file: configure.yml



