---

- name: List CAs to get {{ kf_cas_sub.name }} Id
  register: listcas
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh ca listcas

- name: Parse {{ kf_cas_sub.name }} Id from output
  when: 
    - item is search(kf_sub.name) # identity CA Name: line to get next line which is id
    - item is search('CA Name')
  ansible.builtin.set_fact:
    kf_sub_id: "{{ (ansible_loop.nextitem|split)[1] }}" # split next line and store the second index with the ID
  loop: "{{ listcas.stdout_lines }}"
  loop_control:
    extended: true

- name: Add {{ kf_cas_sub.name }} ID to {{ kf_services.presigner.name }}
  register: update_service
  ansible.builtin.command: >
    {{ kf_ejbca_home }}/bin/ejbca.sh service edit
    --service "{{ kf_services.presigner.name }}"
    --properties worker.caidstocheck={{ kf_sub_id|int }}