---

- name: Generate keys for OCSP Signers on crypto token
  include_role:
    name: ansible-ejbca-crypto-token
    tasks_from: generate_keys
  loop: "{{ ejbca_keybinding |subelements('crypto_token') }}"
  loop_control:
    label: "{{ key_item.0.caname }}"
    loop_var: key_item
  #no_log: "{{ no_log_value }}"
  tags: key_generation
  when:
    - ejbca_keybinding[0] is defined

- name: Create LDAPS Key Binding
  include_role:
    name: ansible-ejbca-key-binding
  vars:
    key_bindings: "{{ ejbca_keybinding }}"
    ldaps_key_bind: true
  when: 
    - ejbca_keybinding[0] is defined

- name: Create a fact for ra_identity_csr_info
  set_fact:
    cacheable: yes
    identity_csr_info: |
      [
      {% for line in ejbca_keybinding %}
      {{ '{' }} 'name':'{{ line.name }}',  
      'dn': '{{ line.dn }}', 
      'caname': '{{ line.caname }}', 
      'token': '{{ line.token }}', 
      'certprofile': '{{ line.certprofile }}', 
      'eeprofile': '{{ line.eeprofile }}' {{ '}' }},
      {% endfor %}
      ]
  when: ejbca_keybinding[0] is defined
  ignore_errors: yes  

- name: Write CSR info to shared vars directory {{ sharedVarsLocation }}/ldaps_key_binding.yml for use with signing LDAPS Key Binding
  become: no
  copy:
    dest: "{{ sharedVarsLocation }}/ldaps_key_binding.yml"
    content: "{{ ra_identity_csr_info| to_nice_yaml }}"
  delegate_to: localhost
  register: write_the_output_ra_signers
  no_log: "{{ no_log_value }}"
  