---

- name: Enable Inbound Peer Connections
  command: >
    {{ ejbca_sh }} peer config 
    --enable-in TRUE 
    --enable-out FALSE
  no_log: "{{ no_log_value }}"
  become: yes
  become_user: "{{ ejbca_user }}"
