---

- name: Check if Elytron Credential store pass exists
  register: elytron_pass_file
  changed_when: false
  ansible.builtin.stat:
    path: "{{ kf_jboss_pass_file }}"

- name: Check if Elytron Credential store file exists
  register: elytron_store_file
  changed_when: false
  ansible.builtin.stat:
    path: "{{ jboss_home }}/standalone/configuration/keystore/jboss.jceks"

- name: Elytron Credential store configuration
  when:
    - not elytron_pass_file.stat.exists or 
      not elytron_store_file.stat.exists
  block:

    - name: Change NSSDB to readWrite
      when: 
        - not elytron_store_file.stat.exists
      ansible.builtin.lineinfile:
        path: /etc/alternatives/jre_openjdk/conf/security/nss.fips.cfg
        regexp: '^nssDbMode = readOnly'
        line: nssDbMode = readWrite
        owner: root
        group: root
        mode: '0644'

    - name: Define a FIPS 140-2 Compliant Credential Store and prevent failure if alias already exists
      when: 
        - not elytron_store_file.stat.exists
      register: fips_compliant_cred_store
      changed_when: true
      failed_when:
        - fips_compliant_cred_store.rc >= 1
        - not fips_compliant_cred_store is search('alias <jboss> already exists')
      ansible.builtin.command: >
        keytool 
        -keystore NONE 
        -storetype PKCS11 
        -storepass {{ kf_vault_nssdb_pass }}
        -genseckey 
        -alias jboss 
        -keyalg AES 
        -keysize 256

    - name: Change NSSDB back to readOnly
      when: 
        - not elytron_store_file.stat.exists
      ansible.builtin.lineinfile:
        path: /etc/alternatives/jre_openjdk/conf/security/nss.fips.cfg
        regexp: '^nssDbMode = readWrite'
        line: nssDbMode = readOnly
        owner: root
        group: root
        mode: '0644'

    - name: Create credential file
      when:
        - not elytron_store_file.stat.exists
      ansible.builtin.template:
        src: wildfly.j2
        dest: "{{ kf_jboss_pass_file }}"
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: '0700'

    - name: Create credential store path
      ansible.builtin.file:
        path: "{{ kf_jboss_credentialstore_path }}"
        state: directory
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: '0770'

    - name: Add DB Password to credential store
      when:
        - not elytron_store_file.stat.exists
      notify: Restart jboss
      no_log: false
      ansible.builtin.command: |
        {{ jboss_home }}/bin/jboss-cli.sh 
        --connect '/subsystem=elytron/credential-store={{ kf_jboss_credentialstore }}:add-alias(alias={{ kf_db_reference }}, secret-value={{ kf_vault_db_pass }})'

    - name: Fix permissions on jceks file
      ansible.builtin.file:
        path: "{{ kf_jboss_credentialstore_file }}"
        mode: '0640'

- name: Add {{ kf_ejbca_user }} to hsmusers group for Thales T-2000
  when: 
    - safenetclient.stat.exists
    - hsm_driver_path is search('safenet')
  ansible.builtin.user:
    name: "{{ kf_ejbca_user }}"
    groups: hsmusers
    append: true